%% Job setup
% Indicate job initialization
disp('~~~~~~~~~~~~~~~~~~~~~job begun!~~~~~~~~~~~~~~~~~~~~~')

% Specify working directory
workdir = '/Users/bterhunecotter/MyDrive/SDSU_LLCN/LOC/6_Results/1-1_gcss_parcels/';
cd(workdir)

%% Select localizer SPM.mat files
% s5 & s6 removed for massive signal dropout
% s11 included because they are an early signer
% s13 excluded because left-handed
% s16 excluded because only two runs
subjects = {...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-01/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-02/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-03/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-04/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-07/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-08/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-09/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-10/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-11/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-12/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-14/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-15/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-17/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-18/SPM.mat',...
    '/Volumes/BTCruiser/LOC/stats_200hpf/sub-19/SPM.mat'...
};

resultsdir = '15sj_N-B_mROIaslhomo_60pROI_ortho_05FDR_4-8fwhm_200hpf';		% rename results directory here

% Set up SPM_SS control structure
ss=struct(...
    'swd',fullfile(workdir,resultsdir),...			% working directory
    'files_spm',{subjects},...							% SPM structures for subjects
    'type','mROI',...									% analysis type
    'ManualROIs',{'/Users/bterhunecotter/MyDrive/SDSU_LLCN/LOC/6_Results/1-1_gcss_parcels/parcelsASL_homologous.nii'},... % manual ROIs used
    'Localizer_contrasts',{{'narr-base - All Sessions'}},...	% names of localizer contrasts in SPM struct
    'EffectOfInterest_contrasts',{{'narr - All Sessions', ...
								   'sent - All Sessions', ...
								   'word - All Sessions', ...
								   'base - All Sessions', ...
								   'sent-word - All Sessions', ...
								   'noun-verb - All Sessions', ...
								   'verb-noun - All Sessions'}},...		% names of effect of interest contrasts in SPM struct
    'Localizer_thr_type','FDR',...						% how to select voxels, e.g. sig threshold, percentile, etc.; e.g. uncorrected sig threshold ('none')
    'Localizer_thr_p',0.05,...							% cutoff defined here, can be p-val, percentile, nvoxels, etc. based on specification above; if automatic, this is disregarded
    'overlap_thr_roi',0.60,...							% minimum proportion of subjects showing a significant localizer effect within an ROI when measuring effect sizes; 0 means don't disregard any ROIs.
    'overlap_thr_vox',0.20,...							% minimum proportion of subjects showing an effect in a voxel when constructing ROI parcellation.
    'smooth',8,...										% smoothing in Gaussian FWHM mm
    'overwrite', 1,...									% overwrite output files if run again
    'model',1,...										% one-sample t-test (for single-group analyses)
    'ExplicitMasking', [], ...							% if you want to apply additional explicit masking to constrain GcSS
    'estimation','ReML',...								% ordinary least squares (OLS) or restricted maximum likelihood (ReML) estimation
    'ask','missing',...									% can be 'none' (any missing information is assumed to take default values), 'missing' (any missing information will be asked to the user), 'all' (it will ask for confirmation on each parameter)
	'orthogonalize','yes'...							% 'no' to avoid orthogonalizing localizer and effect of interest contrasts; default is to orthogonalize
);

%% Run GcSS
ss=spm_ss_design(ss);
disp('ss structure designed!')
ss=spm_ss_estimate(ss);
disp('ss structure estimated!')

%% Job wrapup
% Copy this script to results file
current_script = which(mfilename);						% get the full path of the currently running script
destination = fullfile([workdir resultsdir], '_SPMss_headliner_analysis.m');	% define the destination path
copyfile(current_script, destination);
disp(['headliner script copied to: ', destination]);

% Indicate job completion
disp('~~~~~~~~~~~~~~~~~~~~~job done!~~~~~~~~~~~~~~~~~~~~~')